stages:
    - deploy

deploy:
    before_script:
      - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
      - eval $(ssh-agent -s)
      - echo "$SSH_PRIVATE_KEY"
      - ssh-add <(echo "$SSH_PRIVATE_KEY")
      - mkdir -p ~/.ssh
      - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
    stage: deploy
    image: golang:latest
    script: 
        - go get github.com/constabulary/gb/...
        - gb build
        - mkdir -p build/opt/apptica/bin
        - mv bin/* build/opt/apptica/bin
        - cd build && tar --exclude=apptica.tar.gz -C `pwd` -czvf apptica.tar.gz * && mv apptica.tar.gz ..
        - scp apptica.tar.gz ubuntu@192.168.99.30:/tmp